name: 'Great-Expectations'
description: 'Use Great Expectations https://docs.greatexpectations.io/en/latest/ to validate data.'
inputs:
  CHECKPOINTS:
    description: A comma separated list of checkpoint names to execute.  Example -  "checkpoint1,checkpoint2"
    require: true
branding:
  color: 'gray-dark'
  icon: 'check-circle'
runs:
  using: 'docker'
  image: 'Dockerfile'
