name: 'Great-Expectations'
description: 'Use Great Expectations https://docs.greatexpectations.io/en/latest/ to validate data.'
inputs:
  CHECKPOINTS:
    description: A comma separated list of checkpoint names to execute.  Example -  "checkpoint1,checkpoint2"
    require: true
  NETLIFY_AUTH_TOKEN:
    description: A personal access token for Netlify.
    require: false
  NETLIFY_SITE_ID:
    description: A Netlify site id.
    require: false
  GITHUB_TOKEN:
    description: "Your GITHUB_TOKEN https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#using-the-github_token-in-a-workflow from your Actions Environment."
  AUTO_NETLIFY_DOCS:
    description: Setting this input to any value will trigger this Action to comment on the relevant pull request with a link to a Netlify preview of the Data Docs.  This requires the inputs NETLIFY_AUTH_TOKEN, NETLIFY_SITE_ID, and GITHUB_TOKEN to be specified.
    require: false 
  MANUAL_NETLIFY_DOCS_TRIGGER_PHRASE:
    description: A phrase such as /data-docs that will input as a pull request comment, that will manually trigger a Data Docs build and Deploy to Netlify, and a comment with the resulting link.
    require: false
  DEBUG:
    description: Setting this input to any value will allow the Action to exit with a status code of 0 even if a checkpoint fails.  This is used by maintainers of this Action for testing and debugging.
    require: false
outputs:
  ACTION_DOCS_LOCATION:
    description: The absolute path where generated data docs generated by the Action run are located.  This is useful if you want to deploy the data docs to an external service.
  FAILING_CHECKPOINTS:
    description: A comma delimited list of failed checkpoints.  This will be an empty string if there are no failing checkpoints.
  PASSING_CHECKPOINTS:
    description: A comma delimited list of passing checkpoints.  This will be an empty string if there are no passing checkpoints.
  NETLIFY_DOCS_URL:
    description: The url to the generated data docs on Netlify.  This output is only emitted only if the input parameters NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID are provided.
  CHECKPOINT_FAILURE_FLAG:
    description: This will return 0 if there are no checkpoint failures and 1 if there are one or more checkpoint failures.
branding:
  color: 'gray-dark'
  icon: 'check-circle'
runs:
  using: 'docker'
  image: 'Dockerfile'
