# This is how typical users of Great Expectations can use it for CI in their workflows
name: GE Checkpoints
on: push

test-hosted-action:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@master

    - name: Run Great Expectation Checkpoints
      uses: superconductive/great_expectations_action@master
      with:
        CHECKPOINTS: "passing_checkpoint,failing_checkpoint"
