name: GE-Demo
on: pull_request

jobs:
  demo-pr:
  if: github.event_name == 'pull_request'
  runs-on: ubuntu-latest
  steps:

  - name: Copy Repository Contents
    uses: actions/checkout@master
    with:
        ref: ${{ github.event.pull_request.head.sha }}

  - name: execute local action
    uses: superconductive/great_expectations_action@master
    with:
        CHECKPOINTS: "passing_checkpoint,failing_checkpoint"
