name: GE-Action-Build
on:
  push:
    branches:
      - master
  pull_request: 

jobs:     
  test-local-action:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@master

    - name: execute local action
      continue-on-error: true
      uses: ./
      with:
        CHECKPOINTS: "passing_checkpoint,failing_checkpoint"
      

  test-hosted-action:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@master

    - name: execute local action
      continue-on-error: true
      uses: superconductive/great_expectations_action@master
      with:
        CHECKPOINTS: "passing_checkpoint,failing_checkpoint"
          
  demo-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository Contents
        uses: actions/checkout@master
        with:
            persist-credentials: false

