name: CI
on:
  push:
    branches:
      - master
  pull_request: 

jobs:     
  test-local-action:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@master

    - name: execute local action
      uses: ./
