# A test to see if the GitHub Action is working
# Used for maintainers of this Action.
name: GE-Action-Build
on:
  push:
    branches:
      - master

jobs:     
  test-local-action:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@master

    - name: execute local action
      id: ge
      continue-on-error: true
      uses: ./
      with:
        CHECKPOINTS: "passing_checkpoint,failing_checkpoint"
      
    - name: print location
      run: echo $LOC
      env:
        LOC: ${{ steps.ge.outputs.local_docs_location }}
      

  test-hosted-action:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@master

    - name: execute local action
      continue-on-error: true
      uses: superconductive/great_expectations_action@master
      with:
        CHECKPOINTS: "passing_checkpoint,failing_checkpoint"
          
    - name: print location
      run: echo $LOC
      env:
        LOC: ${{ steps.ge.outputs.local_docs_location }}
